## Numpy array and basics
learn about numpy

In [7]:
import numpy as np


## creating array from list

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : ",arr_1d)

arr_2d = np.array([[1,2,3],[5,4,7]])
print("1D array :\n",arr_2d)

1D array :  [1 2 3 4 5]
1D array :
 [[1 2 3]
 [5 4 7]]


## List vs numpy array

In [9]:
py_list = [1,2,3]
print("multiplication of list : ", py_list*2)

np_array = np.array([1,2,3,11])#element wise multiplication
print("multiplication of array : ", np_array*2)


multiplication of list :  [1, 2, 3, 1, 2, 3]
multiplication of array :  [ 2  4  6 22]


## Creating array from scratch

In [16]:
Zeroes = np.zeros((3,4))
print("zeroes array: \n",Zeroes)

Ones = np.ones((2,4))
print("Ones array matrix:\n",Ones)

full = np.full((2,3),5)
print("full array matrix:\n",full)

random_num = np.random.random((2,3))
print("random:\n",random_num)

sequence = np.arange(0,10,2)
print("sequece array:\n",sequence)


zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array matrix:
 [[5 5 5]
 [5 5 5]]
random:
 [[0.79261701 0.66791453 0.06605913]
 [0.21652855 0.81639663 0.64797856]]
sequece array:
 [0 2 4 6 8]


### Vector , Matrix , Tensor

In [11]:
vector = np.array([1,2,3,4])
print("vector array :\n",vector)

Matrix = np.array([[1,2,3],
                   [6,7,8]])
print("vector Matrix :\n",Matrix)

Tensor = np.array([[[1,2],[3,6]],
                   [[5,8],[9,2]]])
print("vector Tensor :\n",Tensor)

vector array :
 [1 2 3 4]
vector Matrix :
 [[1 2 3]
 [6 7 8]]
vector Tensor :
 [[[1 2]
  [3 6]]

 [[5 8]
  [9 2]]]


## Array Properties

In [18]:
arr = np.array([[[1,2,3],[4,5,6]],
                [[7,5,4],[3,4,9]]])

print("shape :",arr.shape)
print("Dimension :",arr.ndim)
print("size :",arr.size)
print("DType :",arr.dtype)

shape : (2, 2, 3)
Dimension : 3
size : 12
DType : int64


## Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array :",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array :\n",reshaped)

flattened = reshaped.flatten()
print("\n flattened array:\n",flattened)

#ravel (return original,insted of copy)
raveled = reshaped.ravel()
print("\n ravel array:\n",raveled)

#Transposed
transposed = reshaped.T
print("\n rtransposed array:\n",transposed)

Original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 ravel array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 rtransposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
