In [1]:
import numpy as np

## Numpy array operation
### 1D array

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("elemnt at position five is :",arr[4]) #particular elemnt
print("basic slicing :",arr[2:7]) #from pos 2 to 7 it st from 0
print("with step :",arr[1:8:2])
print("negative slicing :",arr[-3]) #piche se 3 pr

elemnt at position five is : 5
basic slicing : [3 4 5 6 7]
with step : [2 4 6 8]
negative slicing : 7


### 2D array

In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("specific element :",arr_2d[1,2]) #target 2 row 3rd column
print("Entire row :",arr_2d[1])
print("Entire column :",arr_2d[:,1])

specific element : 6
Entire row : [4 5 6]
Entire column : [2 5 8]


## Sorted

In [ ]:
sorted = np.array([3,1,4,1,8,7,6])
print("sorted array :",np.sort(sorted))#make in sequence

arr_2d_unsorted = np.array([[3,1],
                            [1,6],
                            [2,3]])
print("sorted 2d array column :\n",np.sort(arr_2d_unsorted , axis=0)) #arrange acc to col only
print("sorted 2d array row :\n",np.sort(arr_2d_unsorted , axis=1)) #arrange acc to row only

sorted array : [1 1 3 4 6 7 8]
sorted 2d array column :
 [[1 1]
 [2 3]
 [3 6]]
sorted 2d array row :
 [[1 3]
 [1 6]
 [2 3]]


## Filter

In [11]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers % 2 == 0]
print("Even number: ",even_num)

Even number:  [ 2  4  6  8 10]


### filter with mask

In [12]:
mask = numbers > 5
print("numbers greter than 5 -->",numbers[mask])

numbers greter than 5 --> [ 6  7  8  9 10]


## Fancy indexting vs np.where()

In [18]:
indices = [0,2,4] #make a type of array from numbers location like 0 --> 1
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where :",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where : [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5,numbers * 2,numbers)#operation apply for greter than 5
print(condition_array)

condition_array = np.where(numbers > 5,"true","false")#(condition,if condition true , else )
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and removing data

In [39]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

add_arr = arr1 + arr2
print(add_arr)
combined = np.concatenate((arr1,arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


### array compatibility 

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,1])

print("Compatibility shapes ",a.shape == b.shape)
print("Compatibility shapes ",a.shape == c.shape)

Compatibility shapes  True
Compatibility shapes  False


In [4]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original,new_row)) # use in adding extra row in matrix

print("original :\n",original)
print("with new row :\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("with new column :\n",with_new_col)

original :
 [[1 2]
 [3 4]]
with new row :
 [[1 2]
 [3 4]
 [5 6]]
with new column :
 [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2) #dlt indexing 2 elemnt
print("Array after deletion --> ",deleted)

Array after deletion -->  [1 2 4 5]
